"""Caddy TLS sidecar — HTTPS-by-default override for the certified install.

PURE OVERRIDE MODULE. v0.4 opt-in hardening. Generates two artifacts inside
the install_dir:

  - docker-compose.tls.yml   (Caddy service definition, named volumes,
                              reverse-proxy ports 443 on the host)
  - Caddyfile                (path-based routing for the 4 main UIs)

NEVER touches the base docker-compose.yml that runner._patch_compose_images()
writes — that file is the FROZEN install path and any change there would
invalidate the certified-stack contract. The override is activated by the
user with an explicit `docker compose -f docker-compose.yml -f
docker-compose.tls.yml up -d caddy` command, surfaced from this module so
the route layer doesn't have to know about compose flag ordering.

Two TLS profiles:

  - self_signed   Caddy generates an internal CA + per-host cert at startup.
                  Works offline. Browser shows a warning unless the operator
                  imports Caddy's root CA — that's an acceptable tradeoff
                  for a default-on dev/pilot install.
  - letsencrypt   Caddy auto-issues via ACME HTTP-01 using the provided
                  domain + email. Requires port 80 + 443 inbound and DNS
                  pointing at the host. Cert + ACME account live in the
                  caddy_data volume — DO NOT recreate that volume on
                  upgrades or you'll burn Let's Encrypt rate-limit budget.

The 4 services proxied (path prefixes, all on one virtual host):

  /minio    → minio:9001       (MinIO console)
  /iceberg  → iceberg-rest:8181 (Iceberg REST catalog)
  /spark    → spark-iceberg:8888 (Spark Jupyter Notebook UI)
  /starrocks → starrocks-fe:8030 (StarRocks FE web UI)

The Caddy container joins the install's default docker network so the
upstream hostnames above resolve. We rely on docker compose convention —
both files share the same `name` derived from the install_dir, which is
how compose merges them.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Literal, Optional

from pydantic import BaseModel, Field, field_validator

from .state import store


log = logging.getLogger("lhs.caddy_tls")


# ---- pinned image tag ----
# Verified via `docker manifest inspect caddy:2.8-alpine` on 2026-05-16.
# Multi-arch (amd64 + arm64). DO NOT use `caddy:latest` — Caddy 3.x will
# introduce config breaks and we want override files to remain valid.
CADDY_IMAGE = "caddy:2.8-alpine"

# Filenames written into the install_dir. The base compose file is
# `docker-compose.yml` (FROZEN); ours is the sibling override.
_OVERRIDE_FILENAME = "docker-compose.tls.yml"
_CADDYFILE_FILENAME = "Caddyfile"


# ---------- models ----------


class TlsProfile(BaseModel):
    """User-facing TLS profile. `self_signed` works offline; `letsencrypt`
    requires a real domain pointing at the host with ports 80+443 reachable
    from the public internet (ACME HTTP-01 challenge)."""
    kind: Literal["self_signed", "letsencrypt"]
    domain: Optional[str] = Field(default=None, max_length=253)
    email: Optional[str] = Field(default=None, max_length=320)

    @field_validator("domain")
    @classmethod
    def _strip_domain(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return v
        v = v.strip().lower()
        return v or None

    @field_validator("email")
    @classmethod
    def _strip_email(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return v
        v = v.strip()
        return v or None


# ---------- compose + Caddyfile rendering ----------


def _render_compose_override() -> str:
    """Render the docker-compose.tls.yml content. Static — the per-profile
    customisation lives in the Caddyfile, not here. Keeping compose stable
    means the operator can flip self_signed <-> letsencrypt by editing the
    Caddyfile alone and running `docker compose ... up -d caddy` again."""
    # Compose merging note: we deliberately do NOT name the top-level
    # `services:` block's network — docker compose merges this override
    # into the base file and the caddy service auto-joins the default
    # `<install>_default` network, which is where minio/iceberg-rest/etc
    # live. Adding an explicit network here would create a SECOND network
    # and break upstream resolution.
    return (
        "# docker-compose.tls.yml -- Caddy TLS sidecar override.\n"
        "# Generated by backend/caddy_tls.py. Activate with:\n"
        "#   docker compose -f docker-compose.yml -f docker-compose.tls.yml up -d caddy\n"
        "# Deactivate with:\n"
        "#   docker compose -f docker-compose.yml -f docker-compose.tls.yml down\n"
        "#\n"
        "# This file is an OVERRIDE. The base docker-compose.yml is FROZEN\n"
        "# (certified-stack contract). Edit the Caddyfile, not this file,\n"
        "# to change routing or TLS behavior.\n"
        "services:\n"
        "  caddy:\n"
        f"    image: {CADDY_IMAGE}\n"
        "    container_name: lhs-caddy\n"
        "    restart: unless-stopped\n"
        "    ports:\n"
        "      # 80 is required for Let's Encrypt ACME HTTP-01 challenge.\n"
        "      # For self_signed installs you can comment it out, but leaving\n"
        "      # it open lets Caddy redirect plain HTTP to HTTPS.\n"
        "      - \"80:80\"\n"
        "      - \"443:443\"\n"
        "    volumes:\n"
        "      - ./Caddyfile:/etc/caddy/Caddyfile:ro\n"
        "      # caddy_data holds the issued certs + ACME account key.\n"
        "      # CRITICAL: do NOT recreate this volume on upgrades --\n"
        "      # losing the ACME account burns Let's Encrypt rate-limit\n"
        "      # budget (5 duplicate certs / week per FQDN).\n"
        "      - caddy_data:/data\n"
        "      - caddy_config:/config\n"
        "volumes:\n"
        "  caddy_data:\n"
        "  caddy_config:\n"
    )


def _render_caddyfile(profile: TlsProfile) -> str:
    """Render the Caddyfile for the requested TLS profile.

    Path-based routing on a single virtual host. We use `handle_path`
    (strips the prefix before forwarding) so upstream services see the
    request rooted at `/`, which matters for MinIO's console + Spark's
    Jupyter (both sensitive to base-path).
    """
    if profile.kind == "self_signed":
        # `localhost` is the canonical name for self-signed installs --
        # the operator can edit the file to add more SANs after the fact.
        site = "localhost"
        tls_directive = (
            "    # Self-signed: Caddy generates an internal CA + per-host\n"
            "    # cert at startup. Import /data/caddy/pki/authorities/local/root.crt\n"
            "    # into your OS trust store to silence browser warnings.\n"
            "    tls internal\n"
        )
    elif profile.kind == "letsencrypt":
        if not profile.domain:
            raise ValueError("letsencrypt requires a domain")
        if not profile.email:
            raise ValueError("letsencrypt requires an email for ACME registration")
        site = profile.domain
        # HTTP-01 only for v0.4. DNS-01 (acme_dns) needs a DNS-provider
        # plugin baked into a custom Caddy image -- explicitly out of scope.
        tls_directive = (
            f"    # Let's Encrypt: ACME HTTP-01 challenge. Requires ports 80+443\n"
            f"    # reachable from the public internet and DNS A/AAAA for {site}\n"
            f"    # pointing at this host. Account email is used for expiry alerts.\n"
            f"    tls {profile.email}\n"
        )
    else:  # pragma: no cover -- guarded by TlsProfile Literal
        raise ValueError(f"unknown TLS kind {profile.kind!r}")

    # All 4 services on one virtual host with path-based routing. We use
    # `handle_path` (which strips the matched prefix) so the upstream sees
    # the request rooted at `/`. MinIO console + Spark Jupyter both expect
    # that.
    return (
        f"# Caddyfile -- generated by backend/caddy_tls.py.\n"
        f"# Profile: {profile.kind}\n"
        f"# Site: {site}\n"
        f"#\n"
        f"# Edit this file freely -- it is NOT regenerated on every install.\n"
        f"# Restart caddy after editing:  docker compose restart caddy\n"
        f"\n"
        f"{site} {{\n"
        f"{tls_directive}"
        f"\n"
        f"    # MinIO Console (object browser, IAM, bucket policies)\n"
        f"    handle_path /minio/* {{\n"
        f"        reverse_proxy minio:9001\n"
        f"    }}\n"
        f"\n"
        f"    # Iceberg REST catalog (table metadata API)\n"
        f"    handle_path /iceberg/* {{\n"
        f"        reverse_proxy iceberg-rest:8181\n"
        f"    }}\n"
        f"\n"
        f"    # Spark + Iceberg Jupyter Notebook UI\n"
        f"    handle_path /spark/* {{\n"
        f"        reverse_proxy spark-iceberg:8888\n"
        f"    }}\n"
        f"\n"
        f"    # StarRocks FE web UI (cluster status, profile, slow queries)\n"
        f"    handle_path /starrocks/* {{\n"
        f"        reverse_proxy starrocks-fe:8030\n"
        f"    }}\n"
        f"\n"
        f"    # Catch-all: tiny landing page so `/` returns something useful\n"
        f"    # instead of a 404 (Caddy's default for an unhandled route).\n"
        f"    handle {{\n"
        f"        respond \"Lakehouse Studio TLS sidecar. Try /minio, /iceberg, /spark, /starrocks.\" 200\n"
        f"    }}\n"
        f"}}\n"
    )


# ---------- public API ----------


def _resolve_install_dir(install_id: str) -> Path:
    """Look up the install_dir for the given install_id, raise if unknown.
    Centralised so both write_caddy_override and disable_caddy_override
    give the same error shape."""
    rec = store.get(install_id)
    if rec is None:
        raise ValueError(f"install {install_id!r} not found")
    install_dir = Path(rec.install_dir)
    if not install_dir.exists():
        raise ValueError(
            f"install_dir {install_dir} does not exist (was the install removed?)"
        )
    return install_dir


async def write_caddy_override(install_id: str, profile: TlsProfile) -> Path:
    """Write the Caddy override + Caddyfile into the install_dir.

    Returns the Path to the docker-compose.tls.yml override file so the
    route layer can echo it back to the UI. The Caddyfile sits next to it.

    Idempotent: re-running with the same install_id overwrites both files
    with the current profile. The operator can then `docker compose ...
    up -d caddy` to apply.
    """
    install_dir = _resolve_install_dir(install_id)
    override_path = install_dir / _OVERRIDE_FILENAME
    caddyfile_path = install_dir / _CADDYFILE_FILENAME

    compose_body = _render_compose_override()
    caddy_body = _render_caddyfile(profile)

    # Write Caddyfile FIRST -- if the compose file is present without the
    # Caddyfile next to it, `caddy up` will fail with a confusing error
    # about a missing config volume. The other order leaves the override
    # half-installed on a crash.
    caddyfile_path.write_text(caddy_body, encoding="utf-8")
    override_path.write_text(compose_body, encoding="utf-8")

    log.info(
        "wrote Caddy override install_id=%s profile=%s domain=%s",
        install_id, profile.kind, profile.domain,
    )
    return override_path


async def disable_caddy_override(install_id: str) -> None:
    """Remove the override file + Caddyfile from the install_dir.

    Caller is responsible for stopping the caddy container FIRST with:
      docker compose -f docker-compose.yml -f docker-compose.tls.yml down

    We don't run that command here -- the FastAPI route layer surfaces
    the deactivate command to the user so they retain control. Removing
    the files without stopping caddy leaves a dangling container that
    docker compose can't reconcile without the override file present.
    """
    install_dir = _resolve_install_dir(install_id)
    override_path = install_dir / _OVERRIDE_FILENAME
    caddyfile_path = install_dir / _CADDYFILE_FILENAME

    for p in (override_path, caddyfile_path):
        try:
            p.unlink(missing_ok=True)
        except Exception as e:
            log.warning("failed to remove %s: %s", p, e)

    log.info("removed Caddy override install_id=%s", install_id)


def is_caddy_enabled(install_id: str) -> bool:
    """Cheap file-existence check. Returns False if the install_id is
    unknown or the install_dir is gone -- we don't raise here because
    callers use this for UI status, not for guarding writes."""
    rec = store.get(install_id)
    if rec is None:
        return False
    override_path = Path(rec.install_dir) / _OVERRIDE_FILENAME
    return override_path.exists()


def caddy_activate_command(install_id: str) -> str:
    """Return the exact command the user runs in the install_dir to bring
    Caddy up. We surface this rather than running it ourselves -- the
    operator needs to see what happens to their stack before TLS flips on.
    """
    # Note: the command is intentionally run from the install_dir, so the
    # paths are relative. Doing it absolute would couple us to the
    # operator's shell pwd resolution.
    return (
        "docker compose -f docker-compose.yml -f docker-compose.tls.yml "
        "up -d caddy"
    )


def caddy_deactivate_command(install_id: str) -> str:
    """Return the granular teardown command. Stops + removes ONLY the caddy
    service so the rest of the stack (MinIO, Iceberg, Spark, StarRocks)
    keeps serving uninterrupted. Operator can then safely remove the
    override file via `caddy_tls.disable_caddy_override()`.
    """
    # Stop + rm narrowly — `compose down` here would clobber the whole
    # stack, which is the bug Gemini's v0.5 review flagged.
    return (
        "docker compose -f docker-compose.yml -f docker-compose.tls.yml "
        "stop caddy && "
        "docker compose -f docker-compose.yml -f docker-compose.tls.yml "
        "rm -f caddy"
    )
